apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-learn-labs
spec:
  title: Learn How to Build a Workshop
  description: Learn How to Build a Workshop
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/eduk8s/lab-markdown-sample
  content:
    image: brianmmcclain/lab-learn-labs:latest
    #files: github.com/BrianMMcClain/lab-learn-labs
  session:
    namespaces:
      budget: small
    
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)

    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true